### ISSUE TITLE
[FEAT] Font & Color Configuration

### ISSUE THREAD

**Issue by WhiteHyun** [PLUB2022/PLUB-iOS#9]
## 📌  Feature Issue

- 기존 `figma`의 font style을 그대로 차용했으나, iOS에서는 body폰트를 `2pt` 올려야될 거 같다는 PM분의 의견을 전달들음
- Color 색상 Configuration 추가

## 📝  To-do

- [x] Font - Body 값 수정
- [x] Color Configuration 설정

**Comment by WhiteHyun** [comment]
## 서로 의논해보아요

<img width="539" alt="image" src="https://user-images.githubusercontent.com/57972338/198540461-5a60655d-1a2f-4f09-8e3d-ae5995cc9b23.png">

Plub에서 제공된 색상코드를 가지고 Configuration 작업을 진행하는데 어떻게 구현할 지에 대한 고민에 빠졌다.

1. main color와 main color2가 있는데 뭔가 **가독성**이 살지 않음
2. Plub의 light gray와 UIColor의 light gray 작명이 겹침(색상은 서로 다름)

## 해결점 찾기

### 문제 1

- main color 2를 그대로 작명하지 않고, subMain으로 작명하는 게 좀 더 가독성이 좋아보이는 것 같다.
```swift
//  ***** uicolor extension에서 static으로 구현해둔 전제로 작성한 코드 *****
// == 그대로 간다면 ==
let title: UILabel = UILabel().then {
  $0.textColor = .main
}
let subTitle: UILabel = UILabel().then {
  $0.textColor = .main2
}

// == 적용된다면 ==
let title: UILabel = UILabel().then {
  $0.textColor = .main
}
let subTitle: UILabel = UILabel().then {
  $0.textColor = .subMain
}


```

### 문제 2

#### 1. UIColor 내부에 `Plub enum`을 추가하여 분리

```swift

extension UIColor {
  enum Plub {
    // color codes...
  }
}

```

그러면 사용할 때 다음과 같이 적용된다.

```swift
let title: UILabel = UILabel()
title.textColor = UIColor.Plub.lightGray // 방법 1
title.textColor = .Plub.lightGray // 방법 2
```

- 장점
   - UIColor.lightGray와 분리하여 적용 가능하며 Plub에서 정의한 색상명도 그대로 유지할 수 있다.
- 단점
   -  한 번 더 타고 들어가야하는 것 때문에 코드 칠 때 귀찮다. 그리고 무엇보다 코드가 안예쁘다.
   - black이나 white의 경우 이미 UIColor에 존재하기 때문에 오히려 통일성이 사라진다. 통일성을 위해서 white나 black을 다시 재정의해서 넣어줘야한다.

#### 2. 변수명을 살짝 바꾼다

light gray를 shallow gray와 같이 다른 작명을 쓰는 것이다.
> shallow gray가 진짜 말도 안되는 K-작명법이긴 한데.. 이거 말고 어떻게 작성해야될 지 모르겠어서 예시로 저렇게 적어두었다.

```swift
let title: UILabel = UILabel()
title.textColor = .shallowGray
title.textColor = .main
```

- 장점
   - `UIColor`단에서 직접 넣을 수 있다. (UIColor.main 뭐 이렇게)
- 단점
   - **K-작명법**

#### 3. Plub의 색상들을 라이브러리마냥 접두어를 쓴다.

예를 들자면 Plub이니 `pl`을 접두어로 쓰는 것이다.

```swift
let title: UILabel = UILabel()
title.textColor = .plMain
title.textColor = .plLightGray
```

- 단점
   - Swift스럽지 않다.

---

여러분들의 생각은 어떠신가요..?
@uujinn @dlrjswns

**Comment by uujinn** [comment]
### 문제 1
- main / subMain 좋습니다. figma 확인해보니 확실히 main1이 많이 쓰이네요.

### 문제 2
- UIColor의 light Gray를 써야할 일이 있을까요? Plub의 light Gray 색상으로 lightGray를 그대로 재정의하면 어떨까요?

깔끔하게 정리해주셔서 감사합니다! 👍

**Comment by WhiteHyun** [comment]
> ### 문제 1
> * main / subMain 좋습니다. figma 확인해보니 확실히 main1이 많이 쓰이네요.
> 
> ### 문제 2
> * UIColor의 light Gray를 써야할 일이 있을까요? Plub의 light Gray 색상으로 lightGray를 그대로 재정의하면 어떨까요?
> 
> 깔끔하게 정리해주셔서 감사합니다! 👍

답변 감사합니다!

지금에서는 UIColor의 lightGray 색상을 쓰진 않는데, 미래에 대한 두려움 때문에 고민을 했습니다. 너무 미래지향적으로 생각했을까요? 하하
만약 불필요하다면, 유진님 말씀대로 재정의하는 게 제일 나은 방향인 거 같아요.
